sudo: required
language: python
cache: pip
python:
- '3.6'
before_install:
- pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
- pip install torchvision
install:
- pip install .
script:
- cd tests
- travis_wait sh run_all.sh
- cd ..
after_success:
- export CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, TRAVIS_TAG=$TRAVIS_TAG, CURRENT_BRANCH=$CURRENT_BRANCH"
- if [[ "$TRAVIS_BRANCH" == "master" ]] || [[ -n "$TRAVIS_TAG" ]]; then GIT_COMMIT="$(git
  rev-parse HEAD)" ; echo "GIT_COMMIT=$GIT_COMMIT" ; PYPROB_VERSION="$(python setup.py
  --version)" ; echo "PYPROB_VERSION=$PYPROB_VERSION" ; docker login -u $DOCKER_USERNAME
  -p $DOCKER_PASSWORD ; docker build -t probprog/pyprob --build-arg PYPROB_VERSION=$PYPROB_VERSION
  --build-arg GIT_COMMIT=$GIT_COMMIT . ; docker tag probprog/pyprob probprog/pyprob:latest
  ; docker push probprog/pyprob:latest ; if [[ -n "$TRAVIS_TAG" ]]; then docker tag
  probprog/pyprob probprog/pyprob:$TRAVIS_TAG ; docker push probprog/pyprob:$TRAVIS_TAG
  ; fi fi
